server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route #payment_route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**          #断言，路径相匹配的进行路由

        - id: payment_route2 #payment_route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**          #断言，路径相匹配的进行路由
            - After=2022-04-03T22:34:55.094+08:00[Asia/Shanghai]  #断言，在指定时间之后进行路由
            #- Before=2022-04-03T22:34:55.094+08:00[Asia/Shanghai] #断言，在指定时间之前进行路由
            #- Between=2022-04-03T22:34:55.094+08:00[Asia/Shanghai],2022-04-06T22:34:55.094+08:00[Asia/Shanghai] #断言，在指定时间之间进行路由
            #- Cookie=username,zzyy #断言，Cookie键值对，键是Cookie的名，值是正则表达式。路径需匹配Cookie名，并满足正则表达式的进行路由
            #- Header=X-Request-Id, \d+ #断言，请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.atguigu.com #断言，一组匹配的域名列表才能路由
            #- Method=GET #断言，按方法类型匹配进行路由
            #- Query=username, \d+ #断言，要有参数名username并且值还要是整数才能路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


