server:
  port: 2001

spring:
  application:
    name: cloud-alibaba-seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.102:8848
#    alibaba:
#      seata:
#        tx-service-group: default
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: leon891022

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
