server:
  port: 2003

spring:
  application:
    name: cloud-alibaba-seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.102:8848
    alibaba:
      seata:
        tx-service-group: default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: leon891022

seata:
  #Seata 应用编号
  application-id: ${spring.application.name}
  #Seata 事务组编号，用于TC集群名
  tx-service-group: ${spring.application.name}-group
  #关闭自动代理
  enable-auto-data-source-proxy: false
  #服务配置项
  service:
    vgroup-mapping:
      cloud-alibaba-seata-account-service-group: default
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.1.102:8848
      group: SEATA_GROUP
      namespace:

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.alibaba.domain

